# Nom de l'application
spring.application.name=project_exam

# Configuration H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL
spring.jpa.show-sql=true

# Activer la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console